if(!document.querySelector('link[href="compact.css"]')){const c=document.createElement('link');c.rel='stylesheet';c.href='compact.css';document.head.append(c)}
const header=document.querySelector('header'),menu=document.querySelector('.menu'),nav=document.querySelector('.navlinks');
const portfolioLinks='<a href="bio.html"><b>Bio</b><span>Profile, education & experience</span></a><a href="research.html"><b>Research & Roadmap</b><span>Six research domains</span></a><a href="code.html"><b>Code</b><span>Datasets, tools & repositories</span></a><a href="papers.html"><b>Papers</b><span>Selected scholarly papers</span></a><a href="books.html"><b>Books</b><span>Book gallery</span></a><a href="publications.html"><b>Publications</b><span>Journals, patents & HKI</span></a><a href="cv.html"><b>CV</b><span>Academic curriculum vitae</span></a><a href="blog.html"><b>Blog</b><span>Notes and updates</span></a><a href="speaking.html"><b>Speaker / Judge</b><span>Talks, moderation & jury roles</span></a>';
if(nav&&!nav.querySelector('.portfolio-menu')){const details=document.createElement('details');details.className='portfolio-menu';details.innerHTML='<summary>Portfolio</summary><div class="portfolio-dropdown">'+portfolioLinks+'</div>';const contact=nav.querySelector('.pill');contact?nav.insertBefore(details,contact):nav.append(details);document.addEventListener('click',e=>{if(!details.contains(e.target))details.open=false})}
window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>15),{passive:true});
if(menu)menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));document.querySelectorAll('#year').forEach(e=>e.textContent=new Date().getFullYear());
if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/')){const main=document.querySelector('main');if(main&&!document.getElementById('portfolio')){const s=document.createElement('section');s.id='portfolio';s.className='portfolio-brand';s.innerHTML='<div class="wrap portfolio-brand-grid"><div><p class="eyebrow">Explore the portfolio</p><h2>Structured for depth,<br><em>ready to grow.</em></h2></div><div class="portfolio-brand-links">'+portfolioLinks+'</div></div>';main.prepend(s)}}
